### ISSUE TITLE
[Feature request]: Varying time to swap

### ISSUE THREAD

**Issue by nordowl** [Matistan/MinecraftDeathSwap#1]
The plugin works really well, thanks for making it!

One idea I had was that it would be nice if the timer was varying.
Currently, a swap always happens after a set amount of time. Maybe you could add an option to the config to specify a range of time, for example 120 to 300 seconds, so that swaps happen more "randomly" and are less predictable if you hide the scoreboard.

Let me know what you think.

**Comment by Matistan** [comment]
That's a cool idea! Will try to implement this. I'm really glad you enjoy the plugin!

**Comment by Matistan** [comment]
Thank you for this suggestion, this has been implemented in the latest release

**Comment by nordowl** [comment]
Awesome, thank you so much! Will definitely try it out in the next session!
